"""Initial schema with projects, agents, tasks, and health_scores

Revision ID: 97e505033b27
Revises: 
Create Date: 2026-02-16 18:36:05.228942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e505033b27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('max_parallel_tasks', sa.Integer(), nullable=False),
    sa.Column('auto_learn', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    op.create_index(op.f('ix_agents_role'), 'agents', ['role'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('variant', sa.String(length=50), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('timeline_weeks', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('budget_spent', sa.Float(), nullable=False),
    sa.Column('target_users', sa.Integer(), nullable=True),
    sa.Column('target_revenue', sa.Float(), nullable=True),
    sa.Column('current_users', sa.Integer(), nullable=False),
    sa.Column('current_revenue', sa.Float(), nullable=False),
    sa.Column('metadata_tags', sa.JSON(), nullable=True),
    sa.Column('metadata_industry', sa.String(length=255), nullable=True),
    sa.Column('metadata_target_market', sa.String(length=255), nullable=True),
    sa.Column('metadata_tech_stack', sa.JSON(), nullable=True),
    sa.Column('metadata_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_created', 'projects', ['created_at'], unique=False)
    op.create_index('idx_project_status_phase', 'projects', ['status', 'phase'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_phase'), 'projects', ['phase'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_variant'), 'projects', ['variant'], unique=False)
    op.create_table('health_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('acquisition_score', sa.Float(), nullable=False),
    sa.Column('acquisition_metrics', sa.JSON(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('engagement_metrics', sa.JSON(), nullable=True),
    sa.Column('revenue_score', sa.Float(), nullable=False),
    sa.Column('revenue_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_project_created', 'health_scores', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_health_scores_created_at'), 'health_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_health_scores_project_id'), 'health_scores', ['project_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_agent_status', 'tasks', ['agent_id', 'status'], unique=False)
    op.create_index('idx_task_status_priority', 'tasks', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_tasks_agent_id'), 'tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_name'), 'tasks', ['name'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_name'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_agent_id'), table_name='tasks')
    op.drop_index('idx_task_status_priority', table_name='tasks')
    op.drop_index('idx_task_agent_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_health_scores_project_id'), table_name='health_scores')
    op.drop_index(op.f('ix_health_scores_created_at'), table_name='health_scores')
    op.drop_index('idx_health_project_created', table_name='health_scores')
    op.drop_table('health_scores')
    op.drop_index(op.f('ix_projects_variant'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_phase'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index('idx_project_status_phase', table_name='projects')
    op.drop_index('idx_project_created', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_role'), table_name='agents')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
